export type TestamentSide = 'old' | 'new' | 'center';

export type CharacterType =
  | 'ancestor'
  | 'patriarch'
  | 'royal'
  | 'prophet'
  | 'priest'
  | 'judge'
  | 'woman'
  | 'apostle'
  | 'witness'
  | 'missionary'
  | 'antagonist'
  | 'christ';

export type CharacterImportance = 'core' | 'major' | 'normal';

export type CharacterGroup = {
  id: string;
  title: string;
  testament: TestamentSide;
  kicker: string;
  theme: string;
  x: number;
  y: number;
  width: number;
  height: number;
};

export type BibleCharacter = {
  id: string;
  name: string;
  testament: TestamentSide;
  era: string;
  group: string;
  type: CharacterType;
  typeLabel: string;
  importance: CharacterImportance;
  x: number;
  y: number;
  summary: string;
  themes: string[];
  scriptures: string[];
  keyRelations: string;
  relatedPeople: string[];
};

export const characterGroups: CharacterGroup[] = [
  {
    id: 'creation',
    title: '创世时代',
    testament: 'old',
    kicker: 'CREATION',
    theme: '创造、堕落、罪、审判、洪水、重新开始',
    x: 42,
    y: 72,
    width: 190,
    height: 154
  },
  {
    id: 'patriarchs',
    title: '族长时代',
    testament: 'old',
    kicker: 'COVENANT',
    theme: '应许、盟约、以色列民族的开始',
    x: 258,
    y: 68,
    width: 222,
    height: 190
  },
  {
    id: 'exodus',
    title: '出埃及时期',
    testament: 'old',
    kicker: 'EXODUS',
    theme: '拯救、律法、会幕、旷野试炼',
    x: 44,
    y: 268,
    width: 196,
    height: 152
  },
  {
    id: 'judges',
    title: '士师时代',
    testament: 'old',
    kicker: 'JUDGES',
    theme: '士师、拯救、混乱时代、王国前夜',
    x: 266,
    y: 288,
    width: 196,
    height: 142
  },
  {
    id: 'kings',
    title: '君王时代',
    testament: 'old',
    kicker: 'KINGDOM',
    theme: '王权、大卫之约、圣殿、智慧与堕落',
    x: 70,
    y: 462,
    width: 206,
    height: 136
  },
  {
    id: 'prophets',
    title: '先知时代',
    testament: 'old',
    kicker: 'PROPHETS',
    theme: '警告、审判、盼望、弥赛亚预言',
    x: 304,
    y: 468,
    width: 208,
    height: 154
  },
  {
    id: 'return',
    title: '被掳归回时代',
    testament: 'old',
    kicker: 'RETURN',
    theme: '被掳、保守、归回、重建',
    x: 134,
    y: 642,
    width: 244,
    height: 118
  },
  {
    id: 'gospels',
    title: '福音书人物',
    testament: 'new',
    kicker: 'GOSPELS',
    theme: '耶稣降生、预备道路、门徒呼召、十字架与复活见证',
    x: 742,
    y: 72,
    width: 390,
    height: 176
  },
  {
    id: 'twelve',
    title: '十二门徒',
    testament: 'new',
    kicker: 'DISCIPLES',
    theme: '被呼召、跟随、跌倒、恢复、见证复活',
    x: 808,
    y: 286,
    width: 284,
    height: 178
  },
  {
    id: 'church',
    title: '初代教会',
    testament: 'new',
    kicker: 'CHURCH',
    theme: '教会建立、殉道、福音扩展',
    x: 732,
    y: 520,
    width: 214,
    height: 142
  },
  {
    id: 'mission',
    title: '宣教与书信',
    testament: 'new',
    kicker: 'MISSION',
    theme: '外邦宣教、保罗书信、教会牧养、福音传播',
    x: 972,
    y: 500,
    width: 214,
    height: 196
  }
];

export const twelveDisciplesLabels = [
  '彼得',
  '约翰',
  '雅各',
  '安得烈',
  '腓力',
  '巴多罗买',
  '马太',
  '多马',
  '雅各',
  '达太',
  '西门',
  '犹大'
];

export const bibleCharacters: BibleCharacter[] = [
  {
    id: 'adam',
    name: '亚当',
    testament: 'old',
    era: '创世时代',
    group: 'creation',
    type: 'ancestor',
    typeLabel: '人类始祖',
    importance: 'normal',
    x: 96,
    y: 130,
    summary: '第一个人，在创造与堕落的故事中开启人类历史。',
    themes: ['创造', '堕落', '代表'],
    scriptures: ['创世记 1-3章', '罗马书 5章'],
    keyRelations: '夏娃、该隐、亚伯、耶稣基督',
    relatedPeople: ['夏娃', '该隐', '亚伯', '耶稣基督']
  },
  {
    id: 'eve',
    name: '夏娃',
    testament: 'old',
    era: '创世时代',
    group: 'creation',
    type: 'woman',
    typeLabel: '始祖女性',
    importance: 'normal',
    x: 176,
    y: 132,
    summary: '人类第一位女性，堕落叙事也开启救赎应许的伏笔。',
    themes: ['创造', '家庭', '应许'],
    scriptures: ['创世记 2-3章'],
    keyRelations: '亚当、该隐、亚伯',
    relatedPeople: ['亚当', '该隐', '亚伯']
  },
  {
    id: 'cain',
    name: '该隐',
    testament: 'old',
    era: '创世时代',
    group: 'creation',
    type: 'antagonist',
    typeLabel: '反面人物',
    importance: 'normal',
    x: 92,
    y: 190,
    summary: '因嫉妒杀害亚伯，显明罪在关系中的扩散。',
    themes: ['罪', '嫉妒', '审判'],
    scriptures: ['创世记 4章'],
    keyRelations: '亚当、夏娃、亚伯',
    relatedPeople: ['亚当', '夏娃', '亚伯']
  },
  {
    id: 'abel',
    name: '亚伯',
    testament: 'old',
    era: '创世时代',
    group: 'creation',
    type: 'witness',
    typeLabel: '信心见证',
    importance: 'normal',
    x: 164,
    y: 190,
    summary: '以信心献祭，成为被纪念的义人见证。',
    themes: ['敬拜', '信心', '义人'],
    scriptures: ['创世记 4章', '希伯来书 11章'],
    keyRelations: '该隐、亚当、夏娃',
    relatedPeople: ['该隐', '亚当', '夏娃']
  },
  {
    id: 'noah',
    name: '挪亚',
    testament: 'old',
    era: '创世时代',
    group: 'creation',
    type: 'patriarch',
    typeLabel: '洪水见证',
    importance: 'major',
    x: 134,
    y: 236,
    summary: '在洪水审判中蒙恩，被保守进入重新开始的世界。',
    themes: ['审判', '拯救', '盟约'],
    scriptures: ['创世记 6-9章'],
    keyRelations: '亚当、亚伯拉罕',
    relatedPeople: ['亚当', '亚伯拉罕']
  },
  {
    id: 'abraham',
    name: '亚伯拉罕',
    testament: 'old',
    era: '族长时代',
    group: 'patriarchs',
    type: 'patriarch',
    typeLabel: '信心族长',
    importance: 'major',
    x: 322,
    y: 126,
    summary: '蒙召离开本地本族，承受后裔、土地与万国得福的应许。',
    themes: ['信心', '盟约', '应许'],
    scriptures: ['创世记 12章', '创世记 15章', '希伯来书 11章'],
    keyRelations: '撒拉、以撒、雅各、耶稣基督',
    relatedPeople: ['撒拉', '以撒', '雅各', '耶稣基督']
  },
  {
    id: 'sarah',
    name: '撒拉',
    testament: 'old',
    era: '族长时代',
    group: 'patriarchs',
    type: 'woman',
    typeLabel: '应许之母',
    importance: 'normal',
    x: 414,
    y: 126,
    summary: '在迟延中经历应许成就，成为以撒的母亲。',
    themes: ['等候', '应许', '家庭'],
    scriptures: ['创世记 17-21章', '希伯来书 11章'],
    keyRelations: '亚伯拉罕、以撒',
    relatedPeople: ['亚伯拉罕', '以撒']
  },
  {
    id: 'isaac',
    name: '以撒',
    testament: 'old',
    era: '族长时代',
    group: 'patriarchs',
    type: 'patriarch',
    typeLabel: '应许之子',
    importance: 'major',
    x: 330,
    y: 182,
    summary: '承接亚伯拉罕之约，应许线从他继续传给雅各。',
    themes: ['献上', '承接', '盟约'],
    scriptures: ['创世记 22章', '创世记 26章'],
    keyRelations: '亚伯拉罕、撒拉、雅各',
    relatedPeople: ['亚伯拉罕', '撒拉', '雅各']
  },
  {
    id: 'jacob',
    name: '雅各',
    testament: 'old',
    era: '族长时代',
    group: 'patriarchs',
    type: 'patriarch',
    typeLabel: '以色列先祖',
    importance: 'major',
    x: 408,
    y: 194,
    summary: '被改名以色列，十二支派的故事从他展开。',
    themes: ['拣选', '改变', '以色列'],
    scriptures: ['创世记 28章', '创世记 32章'],
    keyRelations: '以撒、约瑟、犹大',
    relatedPeople: ['以撒', '约瑟', '犹大']
  },
  {
    id: 'joseph-ot',
    name: '约瑟',
    testament: 'old',
    era: '族长时代',
    group: 'patriarchs',
    type: 'patriarch',
    typeLabel: '被保守者',
    importance: 'normal',
    x: 318,
    y: 244,
    summary: '从被卖到掌权，显明神在苦难中的护理。',
    themes: ['苦难', '饶恕', '护理'],
    scriptures: ['创世记 37章', '创世记 50章'],
    keyRelations: '雅各、犹大、摩西',
    relatedPeople: ['雅各', '犹大', '摩西']
  },
  {
    id: 'judah',
    name: '犹大',
    testament: 'old',
    era: '族长时代',
    group: 'patriarchs',
    type: 'patriarch',
    typeLabel: '家谱线节点',
    importance: 'major',
    x: 424,
    y: 246,
    summary: '大卫和弥赛亚家谱从犹大支派延伸出来。',
    themes: ['支派', '王权', '弥赛亚'],
    scriptures: ['创世记 49章', '马太福音 1章'],
    keyRelations: '雅各、大卫、耶稣基督',
    relatedPeople: ['雅各', '大卫', '耶稣基督']
  },
  {
    id: 'moses',
    name: '摩西',
    testament: 'old',
    era: '出埃及时期',
    group: 'exodus',
    type: 'prophet',
    typeLabel: '先知领袖',
    importance: 'major',
    x: 110,
    y: 320,
    summary: '带领以色列出埃及，领受律法，并在旷野中牧养百姓。',
    themes: ['拯救', '律法', '带领'],
    scriptures: ['出埃及记 3章', '出埃及记 14章', '申命记 34章'],
    keyRelations: '亚伦、米利暗、约书亚、法老',
    relatedPeople: ['亚伦', '米利暗', '约书亚', '法老']
  },
  {
    id: 'aaron',
    name: '亚伦',
    testament: 'old',
    era: '出埃及时期',
    group: 'exodus',
    type: 'priest',
    typeLabel: '祭司',
    importance: 'normal',
    x: 184,
    y: 322,
    summary: '摩西的同工，以色列祭司职分的重要开端。',
    themes: ['祭司', '敬拜', '同工'],
    scriptures: ['出埃及记 4章', '利未记 8章'],
    keyRelations: '摩西、米利暗',
    relatedPeople: ['摩西', '米利暗']
  },
  {
    id: 'miriam',
    name: '米利暗',
    testament: 'old',
    era: '出埃及时期',
    group: 'exodus',
    type: 'woman',
    typeLabel: '女先知',
    importance: 'normal',
    x: 94,
    y: 382,
    summary: '在出埃及赞美和旷野故事中与摩西、亚伦同行。',
    themes: ['赞美', '同行', '旷野'],
    scriptures: ['出埃及记 15章', '民数记 12章'],
    keyRelations: '摩西、亚伦',
    relatedPeople: ['摩西', '亚伦']
  },
  {
    id: 'joshua',
    name: '约书亚',
    testament: 'old',
    era: '出埃及时期',
    group: 'exodus',
    type: 'judge',
    typeLabel: '承接领袖',
    importance: 'major',
    x: 178,
    y: 384,
    summary: '承接摩西带领百姓进入应许之地。',
    themes: ['承接', '勇敢', '应许之地'],
    scriptures: ['约书亚记 1章', '约书亚记 24章'],
    keyRelations: '摩西、撒母耳',
    relatedPeople: ['摩西', '撒母耳']
  },
  {
    id: 'pharaoh',
    name: '法老',
    testament: 'old',
    era: '出埃及时期',
    group: 'exodus',
    type: 'antagonist',
    typeLabel: '对立权势',
    importance: 'normal',
    x: 64,
    y: 344,
    summary: '抵挡以色列出埃及，成为压迫与刚硬的代表。',
    themes: ['压迫', '刚硬', '审判'],
    scriptures: ['出埃及记 5-12章'],
    keyRelations: '摩西、亚伦',
    relatedPeople: ['摩西', '亚伦']
  },
  {
    id: 'deborah',
    name: '底波拉',
    testament: 'old',
    era: '士师时代',
    group: 'judges',
    type: 'judge',
    typeLabel: '士师',
    importance: 'normal',
    x: 320,
    y: 338,
    summary: '在混乱时代中作士师和先知，带领百姓经历拯救。',
    themes: ['士师', '拯救', '勇气'],
    scriptures: ['士师记 4-5章'],
    keyRelations: '基甸、撒母耳',
    relatedPeople: ['基甸', '撒母耳']
  },
  {
    id: 'gideon',
    name: '基甸',
    testament: 'old',
    era: '士师时代',
    group: 'judges',
    type: 'judge',
    typeLabel: '士师',
    importance: 'normal',
    x: 404,
    y: 338,
    summary: '在惧怕中被呼召，经历少数人与神同工的得胜。',
    themes: ['呼召', '软弱', '得胜'],
    scriptures: ['士师记 6-8章'],
    keyRelations: '底波拉、撒母耳',
    relatedPeople: ['底波拉', '撒母耳']
  },
  {
    id: 'ruth',
    name: '路得',
    testament: 'old',
    era: '士师时代',
    group: 'judges',
    type: 'woman',
    typeLabel: '外邦女子',
    importance: 'major',
    x: 320,
    y: 398,
    summary: '以忠诚和信心进入大卫与弥赛亚家谱。',
    themes: ['忠诚', '救赎', '家谱'],
    scriptures: ['路得记', '马太福音 1章'],
    keyRelations: '大卫、耶稣基督',
    relatedPeople: ['大卫', '耶稣基督']
  },
  {
    id: 'samuel',
    name: '撒母耳',
    testament: 'old',
    era: '士师时代',
    group: 'judges',
    type: 'prophet',
    typeLabel: '先知士师',
    importance: 'major',
    x: 404,
    y: 398,
    summary: '士师时代与王国时代之间的关键先知。',
    themes: ['听命', '膏立', '转折'],
    scriptures: ['撒母耳记上 3章', '撒母耳记上 16章'],
    keyRelations: '扫罗、大卫',
    relatedPeople: ['扫罗', '大卫']
  },
  {
    id: 'saul',
    name: '扫罗',
    testament: 'old',
    era: '君王时代',
    group: 'kings',
    type: 'royal',
    typeLabel: '第一任君王',
    importance: 'normal',
    x: 124,
    y: 520,
    summary: '以色列第一任王，因悖逆显出王权的危机。',
    themes: ['王权', '悖逆', '惧怕'],
    scriptures: ['撒母耳记上 9-15章'],
    keyRelations: '撒母耳、大卫',
    relatedPeople: ['撒母耳', '大卫']
  },
  {
    id: 'david',
    name: '大卫',
    testament: 'old',
    era: '君王时代',
    group: 'kings',
    type: 'royal',
    typeLabel: '以色列第二任君王',
    importance: 'major',
    x: 190,
    y: 520,
    summary: '合神心意的王，但也经历严重失败与悔改。',
    themes: ['王权', '敬拜', '悔改', '弥赛亚预表'],
    scriptures: ['撒母耳记上 16章', '撒母耳记下 7章', '诗篇'],
    keyRelations: '扫罗、所罗门、耶稣基督',
    relatedPeople: ['扫罗', '所罗门', '耶稣基督']
  },
  {
    id: 'solomon',
    name: '所罗门',
    testament: 'old',
    era: '君王时代',
    group: 'kings',
    type: 'royal',
    typeLabel: '智慧君王',
    importance: 'normal',
    x: 252,
    y: 520,
    summary: '建造圣殿并以智慧闻名，也显明王国堕落的张力。',
    themes: ['智慧', '圣殿', '堕落'],
    scriptures: ['列王纪上 3章', '列王纪上 8章'],
    keyRelations: '大卫、以斯拉',
    relatedPeople: ['大卫', '以斯拉']
  },
  {
    id: 'elijah',
    name: '以利亚',
    testament: 'old',
    era: '先知时代',
    group: 'prophets',
    type: 'prophet',
    typeLabel: '先知',
    importance: 'major',
    x: 360,
    y: 526,
    summary: '在拜偶像的时代宣告耶和华是神。',
    themes: ['争战', '审判', '复兴'],
    scriptures: ['列王纪上 18章'],
    keyRelations: '耶洗别、施洗约翰',
    relatedPeople: ['耶洗别', '施洗约翰']
  },
  {
    id: 'isaiah',
    name: '以赛亚',
    testament: 'old',
    era: '先知时代',
    group: 'prophets',
    type: 'prophet',
    typeLabel: '弥赛亚先知',
    importance: 'major',
    x: 444,
    y: 526,
    summary: '在审判中宣告盼望，留下清晰的弥赛亚预言。',
    themes: ['圣洁', '盼望', '弥赛亚'],
    scriptures: ['以赛亚书 6章', '以赛亚书 53章'],
    keyRelations: '耶稣基督、耶利米',
    relatedPeople: ['耶稣基督', '耶利米']
  },
  {
    id: 'jeremiah',
    name: '耶利米',
    testament: 'old',
    era: '先知时代',
    group: 'prophets',
    type: 'prophet',
    typeLabel: '流泪先知',
    importance: 'normal',
    x: 360,
    y: 588,
    summary: '在国破前后宣告审判，也预告新约的盼望。',
    themes: ['审判', '新约', '哀恸'],
    scriptures: ['耶利米书 31章'],
    keyRelations: '但以理、以赛亚',
    relatedPeople: ['但以理', '以赛亚']
  },
  {
    id: 'daniel',
    name: '但以理',
    testament: 'old',
    era: '先知时代',
    group: 'prophets',
    type: 'prophet',
    typeLabel: '被掳先知',
    importance: 'normal',
    x: 444,
    y: 588,
    summary: '在被掳之地持守忠心，并看见国度异象。',
    themes: ['忠心', '国度', '异象'],
    scriptures: ['但以理书 6章', '但以理书 7章'],
    keyRelations: '以斯拉、尼希米',
    relatedPeople: ['以斯拉', '尼希米']
  },
  {
    id: 'jezebel',
    name: '耶洗别',
    testament: 'old',
    era: '先知时代',
    group: 'prophets',
    type: 'antagonist',
    typeLabel: '对立人物',
    importance: 'normal',
    x: 496,
    y: 558,
    summary: '推动拜偶像并敌对先知，成为属灵冲突的代表。',
    themes: ['偶像', '逼迫', '冲突'],
    scriptures: ['列王纪上 18-19章'],
    keyRelations: '以利亚',
    relatedPeople: ['以利亚']
  },
  {
    id: 'ezra',
    name: '以斯拉',
    testament: 'old',
    era: '被掳归回时代',
    group: 'return',
    type: 'priest',
    typeLabel: '文士祭司',
    importance: 'normal',
    x: 194,
    y: 706,
    summary: '带领百姓重新归回律法与敬拜秩序。',
    themes: ['律法', '归回', '更新'],
    scriptures: ['以斯拉记 7章', '尼希米记 8章'],
    keyRelations: '尼希米、以斯帖',
    relatedPeople: ['尼希米', '以斯帖']
  },
  {
    id: 'nehemiah',
    name: '尼希米',
    testament: 'old',
    era: '被掳归回时代',
    group: 'return',
    type: 'judge',
    typeLabel: '重建领袖',
    importance: 'normal',
    x: 262,
    y: 706,
    summary: '带领重建城墙，恢复群体身份与敬拜生活。',
    themes: ['重建', '祷告', '群体'],
    scriptures: ['尼希米记 1-6章'],
    keyRelations: '以斯拉、但以理',
    relatedPeople: ['以斯拉', '但以理']
  },
  {
    id: 'esther',
    name: '以斯帖',
    testament: 'old',
    era: '被掳归回时代',
    group: 'return',
    type: 'woman',
    typeLabel: '被保守者',
    importance: 'normal',
    x: 328,
    y: 706,
    summary: '在危机中被兴起，见证神对百姓的保守。',
    themes: ['保守', '勇气', '使命'],
    scriptures: ['以斯帖记 4章'],
    keyRelations: '以斯拉、尼希米',
    relatedPeople: ['以斯拉', '尼希米']
  },
  {
    id: 'jesus',
    name: '耶稣基督',
    testament: 'center',
    era: '福音核心',
    group: 'center',
    type: 'christ',
    typeLabel: '弥赛亚',
    importance: 'core',
    x: 600,
    y: 398,
    summary: '旧约应许的成全者，新约见证与教会使命的中心。',
    themes: ['救赎', '国度', '复活', '弥赛亚'],
    scriptures: ['马太福音 1章', '约翰福音 1章', '路加福音 24章'],
    keyRelations: '亚伯拉罕、大卫、彼得、约翰、保罗',
    relatedPeople: ['亚伯拉罕', '大卫', '彼得', '约翰', '保罗']
  },
  {
    id: 'mary',
    name: '马利亚',
    testament: 'new',
    era: '福音书人物',
    group: 'gospels',
    type: 'woman',
    typeLabel: '耶稣母亲',
    importance: 'major',
    x: 810,
    y: 126,
    summary: '以顺服回应呼召，见证耶稣降生与早期教会等候。',
    themes: ['顺服', '降生', '等候'],
    scriptures: ['路加福音 1章', '约翰福音 2章', '使徒行传 1章'],
    keyRelations: '约瑟、耶稣基督',
    relatedPeople: ['约瑟', '耶稣基督']
  },
  {
    id: 'joseph-nt',
    name: '约瑟',
    testament: 'new',
    era: '福音书人物',
    group: 'gospels',
    type: 'witness',
    typeLabel: '义人',
    importance: 'normal',
    x: 888,
    y: 126,
    summary: '在耶稣降生故事中顺服神的引导，保护家庭。',
    themes: ['顺服', '守护', '降生'],
    scriptures: ['马太福音 1-2章'],
    keyRelations: '马利亚、耶稣基督',
    relatedPeople: ['马利亚', '耶稣基督']
  },
  {
    id: 'john-baptist',
    name: '施洗约翰',
    testament: 'new',
    era: '福音书人物',
    group: 'gospels',
    type: 'prophet',
    typeLabel: '预备道路',
    importance: 'major',
    x: 980,
    y: 126,
    summary: '在旷野呼喊悔改，为基督预备道路。',
    themes: ['悔改', '预备', '见证'],
    scriptures: ['马太福音 3章', '约翰福音 1章'],
    keyRelations: '耶稣基督、以利亚',
    relatedPeople: ['耶稣基督', '以利亚']
  },
  {
    id: 'peter',
    name: '彼得',
    testament: 'new',
    era: '福音书人物',
    group: 'gospels',
    type: 'apostle',
    typeLabel: '使徒',
    importance: 'major',
    x: 820,
    y: 196,
    summary: '从热心、跌倒到恢复，成为初代教会重要见证人。',
    themes: ['跟随', '跌倒', '恢复'],
    scriptures: ['马太福音 16章', '约翰福音 21章', '使徒行传 2章'],
    keyRelations: '耶稣基督、约翰、保罗',
    relatedPeople: ['耶稣基督', '约翰', '保罗']
  },
  {
    id: 'john',
    name: '约翰',
    testament: 'new',
    era: '福音书人物',
    group: 'gospels',
    type: 'apostle',
    typeLabel: '使徒',
    importance: 'major',
    x: 900,
    y: 202,
    summary: '亲近主并见证十字架、复活与爱的命令。',
    themes: ['爱', '见证', '启示'],
    scriptures: ['约翰福音 13章', '约翰福音 19章', '启示录 1章'],
    keyRelations: '耶稣基督、彼得',
    relatedPeople: ['耶稣基督', '彼得']
  },
  {
    id: 'james-apostle',
    name: '雅各',
    testament: 'new',
    era: '十二门徒',
    group: 'twelve',
    type: 'apostle',
    typeLabel: '使徒',
    importance: 'normal',
    x: 985,
    y: 332,
    summary: '西庇太的儿子，与彼得、约翰同属耶稣亲近门徒圈。',
    themes: ['门徒', '见证', '代价'],
    scriptures: ['马可福音 5章', '使徒行传 12章'],
    keyRelations: '耶稣基督、约翰、彼得',
    relatedPeople: ['耶稣基督', '约翰', '彼得']
  },
  {
    id: 'andrew',
    name: '安得烈',
    testament: 'new',
    era: '十二门徒',
    group: 'twelve',
    type: 'apostle',
    typeLabel: '使徒',
    importance: 'normal',
    x: 1044,
    y: 352,
    summary: '彼得的兄弟，常把人带到耶稣面前。',
    themes: ['引荐', '跟随', '门徒'],
    scriptures: ['约翰福音 1章', '约翰福音 6章'],
    keyRelations: '耶稣基督、彼得',
    relatedPeople: ['耶稣基督', '彼得']
  },
  {
    id: 'matthew',
    name: '马太',
    testament: 'new',
    era: '十二门徒',
    group: 'twelve',
    type: 'apostle',
    typeLabel: '使徒',
    importance: 'normal',
    x: 1000,
    y: 414,
    summary: '从税吏被呼召成为门徒，见证恩典进入边缘人群。',
    themes: ['呼召', '恩典', '见证'],
    scriptures: ['马太福音 9章'],
    keyRelations: '耶稣基督、十二门徒',
    relatedPeople: ['耶稣基督', '十二门徒']
  },
  {
    id: 'thomas',
    name: '多马',
    testament: 'new',
    era: '十二门徒',
    group: 'twelve',
    type: 'apostle',
    typeLabel: '使徒',
    importance: 'normal',
    x: 1064,
    y: 418,
    summary: '在疑惑中被复活主亲自坚固，作出信心告白。',
    themes: ['疑惑', '复活', '告白'],
    scriptures: ['约翰福音 20章'],
    keyRelations: '耶稣基督、十二门徒',
    relatedPeople: ['耶稣基督', '十二门徒']
  },
  {
    id: 'judas-iscariot',
    name: '犹大',
    testament: 'new',
    era: '十二门徒',
    group: 'twelve',
    type: 'antagonist',
    typeLabel: '背叛者',
    importance: 'normal',
    x: 1116,
    y: 382,
    summary: '十二门徒之一，却以背叛显出人心与救赎事件的黑暗张力。',
    themes: ['背叛', '警醒', '冲突'],
    scriptures: ['马太福音 26章', '约翰福音 13章'],
    keyRelations: '耶稣基督、十二门徒',
    relatedPeople: ['耶稣基督', '十二门徒']
  },
  {
    id: 'mary-magdalene',
    name: '抹大拉的马利亚',
    testament: 'new',
    era: '福音书人物',
    group: 'gospels',
    type: 'woman',
    typeLabel: '复活见证',
    importance: 'normal',
    x: 1010,
    y: 198,
    summary: '在十字架与空坟墓叙事中成为复活的重要见证人。',
    themes: ['见证', '复活', '忠心'],
    scriptures: ['路加福音 8章', '约翰福音 20章'],
    keyRelations: '耶稣基督、彼得、约翰',
    relatedPeople: ['耶稣基督', '彼得', '约翰']
  },
  {
    id: 'pharisees',
    name: '法利赛人',
    testament: 'new',
    era: '福音书人物',
    group: 'gospels',
    type: 'antagonist',
    typeLabel: '宗教对立',
    importance: 'normal',
    x: 1094,
    y: 186,
    summary: '在福音书中常与耶稣发生关于律法、权柄与心灵真实的冲突。',
    themes: ['律法', '假冒', '冲突'],
    scriptures: ['马太福音 23章', '约翰福音 9章'],
    keyRelations: '耶稣基督',
    relatedPeople: ['耶稣基督']
  },
  {
    id: 'stephen',
    name: '司提反',
    testament: 'new',
    era: '初代教会',
    group: 'church',
    type: 'witness',
    typeLabel: '殉道见证',
    importance: 'normal',
    x: 790,
    y: 584,
    summary: '初代教会中的见证人，以殉道推动福音继续扩展。',
    themes: ['殉道', '见证', '圣灵'],
    scriptures: ['使徒行传 6-7章'],
    keyRelations: '腓利、保罗',
    relatedPeople: ['腓利', '保罗']
  },
  {
    id: 'philip-evangelist',
    name: '腓利',
    testament: 'new',
    era: '初代教会',
    group: 'church',
    type: 'missionary',
    typeLabel: '传福音者',
    importance: 'normal',
    x: 858,
    y: 584,
    summary: '把福音带向撒马利亚和旷野路上的外邦寻求者。',
    themes: ['福音扩展', '引导', '外邦'],
    scriptures: ['使徒行传 8章'],
    keyRelations: '司提反、彼得',
    relatedPeople: ['司提反', '彼得']
  },
  {
    id: 'barnabas',
    name: '巴拿巴',
    testament: 'new',
    era: '初代教会',
    group: 'church',
    type: 'missionary',
    typeLabel: '劝慰之子',
    importance: 'major',
    x: 910,
    y: 630,
    summary: '接纳并扶持保罗，也参与早期宣教拓展。',
    themes: ['接纳', '同工', '宣教'],
    scriptures: ['使徒行传 9章', '使徒行传 13章'],
    keyRelations: '保罗、马可',
    relatedPeople: ['保罗', '马可']
  },
  {
    id: 'paul',
    name: '保罗',
    testament: 'new',
    era: '宣教与书信',
    group: 'mission',
    type: 'apostle',
    typeLabel: '外邦使徒',
    importance: 'major',
    x: 1036,
    y: 552,
    summary: '从逼迫者转为使徒，推动外邦宣教并写下多封书信。',
    themes: ['转变', '宣教', '书信', '教会'],
    scriptures: ['使徒行传 9章', '使徒行传 16章', '腓立比书 3章'],
    keyRelations: '巴拿巴、提摩太、提多、路加、马可',
    relatedPeople: ['巴拿巴', '提摩太', '提多', '路加', '马可']
  },
  {
    id: 'timothy',
    name: '提摩太',
    testament: 'new',
    era: '宣教与书信',
    group: 'mission',
    type: 'missionary',
    typeLabel: '年轻同工',
    importance: 'normal',
    x: 1008,
    y: 620,
    summary: '保罗亲密同工，承担教会牧养与教导责任。',
    themes: ['传承', '牧养', '忠心'],
    scriptures: ['提摩太前书', '提摩太后书'],
    keyRelations: '保罗、提多',
    relatedPeople: ['保罗', '提多']
  },
  {
    id: 'titus',
    name: '提多',
    testament: 'new',
    era: '宣教与书信',
    group: 'mission',
    type: 'missionary',
    typeLabel: '教会牧者',
    importance: 'normal',
    x: 1070,
    y: 620,
    summary: '保罗同工，参与教会治理与牧养。',
    themes: ['治理', '牧养', '传承'],
    scriptures: ['提多书', '哥林多后书 8章'],
    keyRelations: '保罗、提摩太',
    relatedPeople: ['保罗', '提摩太']
  },
  {
    id: 'luke',
    name: '路加',
    testament: 'new',
    era: '宣教与书信',
    group: 'mission',
    type: 'witness',
    typeLabel: '医生作者',
    importance: 'normal',
    x: 1128,
    y: 552,
    summary: '记录福音书与使徒行传，见证福音扩展脉络。',
    themes: ['记录', '见证', '宣教'],
    scriptures: ['路加福音', '使徒行传'],
    keyRelations: '保罗、马可',
    relatedPeople: ['保罗', '马可']
  },
  {
    id: 'mark',
    name: '马可',
    testament: 'new',
    era: '宣教与书信',
    group: 'mission',
    type: 'witness',
    typeLabel: '福音书作者',
    importance: 'normal',
    x: 1128,
    y: 620,
    summary: '曾与保罗和巴拿巴同行，后来再次被接纳为有益同工。',
    themes: ['恢复', '记录', '同工'],
    scriptures: ['使徒行传 12-15章', '提摩太后书 4章'],
    keyRelations: '保罗、巴拿巴、路加',
    relatedPeople: ['保罗', '巴拿巴', '路加']
  },
  {
    id: 'aquila',
    name: '亚居拉',
    testament: 'new',
    era: '宣教与书信',
    group: 'mission',
    type: 'missionary',
    typeLabel: '帐棚同工',
    importance: 'normal',
    x: 1018,
    y: 680,
    summary: '与百基拉一起接待、教导并支持宣教工作。',
    themes: ['同工', '家庭', '教导'],
    scriptures: ['使徒行传 18章', '罗马书 16章'],
    keyRelations: '百基拉、保罗',
    relatedPeople: ['百基拉', '保罗']
  },
  {
    id: 'priscilla',
    name: '百基拉',
    testament: 'new',
    era: '宣教与书信',
    group: 'mission',
    type: 'woman',
    typeLabel: '教导同工',
    importance: 'normal',
    x: 1092,
    y: 680,
    summary: '与亚居拉同工，帮助亚波罗更准确明白主道。',
    themes: ['同工', '教导', '接待'],
    scriptures: ['使徒行传 18章', '罗马书 16章'],
    keyRelations: '亚居拉、保罗',
    relatedPeople: ['亚居拉', '保罗']
  }
];
